//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_USER
    {
        public int IDACC { get; set; }
        public Nullable<int> MANV { get; set; }
        public string USERACC { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> TENROLE { get; set; }
    }
}
